import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.tempHeader}>
        <a href='/contact'>Contact</a>
        <a href='/about'>About</a>
        <a href='/services'>Services</a>
      </div>

      <h6 className={styles.title}>This the home page of this demo application</h6>
      <h6 className={styles.main}>We build from here</h6>

    </div>
  )
}
